CREATE TABLE RS3
   ("D" DATE, 
	"S" VARCHAR2(8 BYTE), 
	"C" NUMBER, 
	"V" NUMBER, 
	"RS" NUMBER, 
	"O" NUMBER, 
	"LN" NUMBER, 
	"NXT_O" NUMBER, 
	"NXT_D" DATE, 
	"SMA100" NUMBER, 
	"VMA20" NUMBER, 
	"TR" NUMBER, 
	"PCT_RNK" NUMBER, 
	"DYS_LSTD" NUMBER, 
	"SPX_SMA200_YN" CHAR(1 BYTE), 
	"SPX_SMA100_YN" CHAR(1 BYTE), 
	"SPX_SMA50_YN" CHAR(1 BYTE), 
	"SLOPE" NUMBER, 
	"ANNUALIZED_SLOPE" NUMBER, 
	"R2" NUMBER, 
	"ADJ_SLOPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IE_RS3_D_S_C_V
--------------------------------------------------------

  CREATE INDEX "TEST2"."IE_RS3_D_S_C_V" ON "TEST2"."RS3" ("D", "S", "C", "V") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IE_RS3_S_D_C_V
--------------------------------------------------------

  CREATE INDEX "TEST2"."IE_RS3_S_D_C_V" ON "TEST2"."RS3" ("S", "D", "C", "V") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IE_RS3_D_TO_CHAR
--------------------------------------------------------

  CREATE INDEX "TEST2"."IE_RS3_D_TO_CHAR" ON "TEST2"."RS3" (TO_CHAR("D",'yyyymmdd')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RS3_TO_CHAR_D_SMA200_Y
--------------------------------------------------------

  CREATE INDEX "TEST2"."RS3_TO_CHAR_D_SMA200_Y" ON "TEST2"."RS3" ("D", TO_CHAR("D",'yyyymmdd'), "SPX_SMA200_YN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RS3
--------------------------------------------------------

  ALTER TABLE "TEST2"."RS3" ADD PRIMARY KEY ("D", "S")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
